server:
  port: 8080

spring:
  cloud:
    gcp:
      sql:
        database-name: deviot
        instance-connection-name: loaders-227115:us-central1:deviot
  datasource:
    username: root
    password: root

management:
  endpoints:
    web:
      exposure:
        include: "*"
